### ISSUE TITLE
Milestone 9

### ISSUE THREAD

**Issue by afraznein** [SCCapstone/Hydration-Manager#114]
**Milestone 9**

Watch the [Git and Github lectures](https://cse.sc.edu/capstone/slides/git-github)

By this date you should have:

- [x] Setup your github email correctly. Your most recent commits do not show a grey octocat avatar in github.

![github email setup](https://user-images.githubusercontent.com/23198422/31963645-6dd653ce-b8cf-11e7-8292-ff70bc714dd3.png)

- [x] Have a shared git repo in github,
- [x] The code in the repo builds, something.
- [ ] Every team member can check out the code, build it, and run it on their laptop.
- [ ] Every team member has made a change to the code and pushed it to github.
- [ ] Every team member has pulled in changes from other members.
- [ ] Every team member has experienced and resolved a merge conflict.
> For the merge conflict just have someone else in the time change some line in the code and push it. Then, before you pull, make sure you change that same line (to something else) and commit it. Then try to pull. You will see a merge conflict. Resolve it. Commit your changes. Push.

**Deliverables**

You have to be able to

- [x] pull from the shared repo,
- [x] build,
- [x] run application locally (laptop or emulator)
- [x] commit to shared repo,
- [x] push to the shared repo,
- [ ] merge your branch into master, via pull request or regular merge,
- [ ] and resolve a merge conflict.

**Grading Rubric**
Minimum grade is 0. No negatives!

| Deliverable   | Points Lost   |
| ------------- | ------------- |
| Username appears in git log or repo on github.  | 100 |
| Git/github email setup correctly to match.  | 50 |
| Can build and run code on laptop. Show during our meeting.  | 100 |
| User has Merge commit (two parents) in github log.  | 30 |
