### ISSUE TITLE
Milestone Ten - Master

### ISSUE THREAD

**Issue by afraznein** [SCCapstone/Hydration-Manager#116]
https://github.com/SCCapstone/Hydration-Manager/milestone/10

I parsed over the issues that we had, and removed Milestone 10 category from many of them. We're down to a rough total of 30 issues now, from ~65-70. Please use the above hyperlink to go check out the issues still associated with it. I'm creating this issue so we can all get on board with what we need to finish before December 8th. I figured we could use this issue as a **master issue checklist** for our _Proof of Concept Milestone_. 

Here's what I'm thinking: We can't really do anything on this without a working 'database'. #44 

So at the very least, I feel that we need to implement the following:

- [ ] Users #45 #46 #47 #48

- [ ] Teams #49 #50 #51 #52 

- [ ] Athletes (with baseline weight) #57 #58 #59 #60 #62

- [ ] Data Entry #106 #107

I figured we could also strive to implement the following by the end of this Milestone as well:

- [ ] Working Login Screen #63 #64

- [ ] 'Barebones' Dashboard #85 #86 #87 

- [ ] Add Teams, Athletes in app #98 #99 #100 #101 #102 #103 #104 #105 

- [ ] Deployment #117

If anyone has any suggestions, thinks this is too much, or too little, please feel free to add your comments here. Just trying to stay ahead of this stuff. Thanks guys.
