### ISSUE TITLE
Milestone 7

### ISSUE THREAD

**Issue by afraznein** [SCCapstone/Hydration-Manager#34]
This may be slightly redundant, but Vidal provided us with this checklist for Milestone 7, figured I would add it here. Only remove yourself from this assignment once your other issues for Milestone 7 are finished.

- [x] Create Requirements page
- [x] All features are numbered
- [x] All the major features required by the client are covered in the list.
- [x] The order roughly matches the preferences of the client, or features have been otherwise marked to reflect preferences.
- [x] Features are described in enough detail so as to be unambiguous.
- [x] All the proof-of-concept issues have been added to Issues and associated with proof-of-concept milestone.
- [x] Detailed Design images are linked or embedded in the wiki page, and hosted at github.
- [x] The wiki page is easy to read.
