### ISSUE TITLE
Client Requirements Checklist

### ISSUE THREAD

**Issue by afraznein** [SCCapstone/Hydration-Manager#43]
- [x] The app will provide an interface for athletic training students to enter pre and post practice/game weights
- [x] Show Hydration levels in university varsity athletes
- [x] Use their hydration level to monitor them and help spot trouble athletes (Red,Yellow)
- [x] Send alerts(SMS/email) if a players reaches a red or yellow status
- [x] Show long period weight gain and loss
